FIX
ERROR in ../node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts:71:40 - error TS2339: Property 'closeButtonHtml' does not exist on type 'SweetAlertOptions'.

71     closeButtonHtml: SweetAlertOptions['closeButtonHtml'];
                                          ~~~~~~~~~~~~~~~~~
../node_modules/@sweetalert2/ngx-sweetalert2/lib/swal.component.d.ts:93:41 - error TS2339: Property 'scrollbarPadding' does not exist on type 'SweetAlertOptions'.

93     scrollbarPadding: SweetAlertOptions['scrollbarPadding'];